### ISSUE TITLE
CSV-only column options still appear in column_names_filter

### ISSUE THREAD

**Issue by corejh** [bogdan/datagrid#158]
I have a few columns with `html: false` set but they still show up on my column_names_filter. 

`column_names_filter(header: "Show More Columns", checkboxes: true)`

I understand I can work around this by specifying columns with the `column_names_filter select` option, but I feel like hiding `html: false` checkboxes really should be default.

**Comment by bogdan** [comment]
If you hide them, how would you enable them in CSV? If they are not html and not in column names selection, they must be `mandatory: true`. It will make column impossible to hide and not present in column names selection. 

I don't think it should be the default: how would you manage enabled columns in CSV otherwise.
If you want to change the behavior in your project, you can add the following to the base class of all your grids:

``` ruby
class BaseGrid
  ...
  def self.column(name, options = {}, &block)
    options  = options.reverse_merge(mandatory: true) if options[:html] == false
    super(name, options, &block)
  end
end
```

If you don't want to manage columns for CSV and want all of them to be enabled by default all the time, add the following before csv export in your controller:

``` ruby
@grid.column_names = @grid.available_columns.map(&:name)
render text: @grid.to_csv
```

**Comment by corejh** [comment]
Ah, you're right. My use case was different than the general I believe. I have multiple versions of the same columns for html and cvs.
